_BASE_: [
  '../datasets/coco_detection_m3fd_vis.yml',
  '../runtime3.yml',
  '_base_/optimizer_1x.yml',
  '_base_/dino_r50.yml',
  '_base_/dino_reader.yml',
]

weights: output/dino_r50_4scale_1x_coco/model_final
find_unused_parameters: True
log_iter: 100
