_BASE_: [
  '../datasets/coco_detection_m3fd_visir_new.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/ms_groupx4_rtdetr_v3_rank_r50vd.yml',
  '_base_/multi_rtdetr_reader.yml',
]

weights: output/rtdetr_r50vd_6x_coco/model_final
find_unused_parameters: True
log_iter: 200
