_BASE_: [
  '../datasets/coco_detection_VEDAI.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/ms_rtdetr_v2_r50vd_3level.yml',
  '_base_/multi_rtdetr_reader_1024.yml',
]

weights: output/rtdetr_r50vd_6x_coco/model_final
find_unused_parameters: True
log_iter: 200
