_BASE_: [
  '../datasets/coco_detection_m3fd_visir.yml',
  '../runtime2.yml',
  '_base_/optimizer_6x.yml',
  '_base_/ms_rtdetr_v2_r50vd_learnquery.yml',
  '_base_/multi_rtdetr_reader.yml',
]

weights: output/rtdetr_r50vd_6x_coco/model_final
find_unused_parameters: True
log_iter: 200
