_BASE_: [
  '../datasets/sealand_single_tower_radarcamera_4km_super4_1536_route_roi.yml',
  '../runtime_radar.yml',
  '_base_/sealand_radardetr_reader_r1536_c1024x512_super4.yml',
  '_base_/radardetr_r50vd_route_roi_p2.yml',
]

epoch: 30
metric: RBOX_COCO_STYLE
iou_thresholds: [0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90]
enable_ship_only_eval: True
record_eval_history: True
eval_history_file: eval_history.jsonl
stop_on_nonfinite_loss: True
save_dir: output/sealand_radardetr_r50vd_route_roi_p2_30e_bs2x4_fp32_onlineval_4km_super4_r1536_c1024x512
weights: output/sealand_radardetr_r50vd_route_roi_p2_16e_bs2x4_fp32_test400_onlineval_4km_super4_r1536_c1024x512/sealand_radardetr_r50vd_route_roi_p2_16e_bs2x4_fp32_test400_onlineval_4km_super4_r1536_c1024x512/best_model
find_unused_parameters: True
convert_sync_bn: False
log_iter: 20
snapshot_epoch: 1
worker_num: 4

# If AP50 is very close, prefer higher mAP50:90.
best_model_ap50_tie_margin: 0.005

# Must match radar resize target for stable decoder anchors at eval time.
eval_size: [1536, 1536]

TrainReader:
  batch_size: 1

EvalReader:
  batch_size: 1

EvalDataset:
  !CameraRadar_COCODataSet
    dataset_dir: /data1/zuokun/code/USV/Unmanned_ship_RTDETR/prepared/sealand_single_tower_4km_super4_1536_route_roi
    radar_image_dir: ''
    camera_image_dir: ''
    anno_path: test_onlineval_random400_seed20260327.json
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly', 'gt_primary_camera', 'gt_visible_cameras', 'gt_camera_box_2d', 'gt_has_camera_box']
    allow_empty: true

LearningRate:
  base_lr: 0.00004
  schedulers:
    - !CosineDecay
      max_epochs: 30
      use_warmup: true
    - !LinearWarmup
      start_factor: 0.001
      steps: 2000

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
