_BASE_: [
  'sealand_radardetr_r50vd_6x_4km_super4_960.yml',
]

epoch: 50
save_dir: output/sealand_radardetr_r50vd_50e_bs2_4km_super4_960
weights: output/sealand_radardetr_r50vd_50e_bs2_4km_super4_960/model_final

TrainReader:
  batch_size: 2

LearningRate:
  base_lr: 0.0002
