metric: COCO
num_classes: 6

TrainDataset:
  name: Mutisprctral_COCODataSet
  vis_image_dir: train_vis_img
  ir_image_dir : train_ir_img
  anno_path: annotations/m3fd_train_for_detron2.json
  dataset_dir: /home/guojunjie/PycharmProjects/pp_detection/PaddleDetection-develop/dataset/coco_m3fd_visir
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: Mutisprctral_COCODataSet
  vis_image_dir: val_vis_img
  ir_image_dir: val_ir_img
  anno_path: annotations/m3fd_val_for_detron2.json
  dataset_dir: /home/guojunjie/PycharmProjects/pp_detection/PaddleDetection-develop/dataset/coco_m3fd_visir
  allow_empty: true

TestDataset:
  name: Multi_ImageFolder
  anno_path: annotations/label_list.txt # also support txt (like VOC's label_list.txt)
  dataset_dir: /home/guojunjie/PycharmProjects/pp_detection/PaddleDetection-develop/dataset/coco_m3fd_visir # if set, anno_path will be 'dataset_dir/anno_path'
