metric: RBOX
num_classes: 4

TrainDataset:
  !CameraRadar_COCODataSet
    dataset_dir: /data1/zuokun/code/USV/Unmanned_ship_RTDETR_v2/prepared/sealand_single_tower_4km_super4
    radar_image_dir: ''
    camera_image_dir: ''
    anno_path: train_coco.json
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']
    allow_empty: true

EvalDataset:
  !CameraRadar_COCODataSet
    dataset_dir: /data1/zuokun/code/USV/Unmanned_ship_RTDETR_v2/prepared/sealand_single_tower_4km_super4
    radar_image_dir: ''
    camera_image_dir: ''
    anno_path: valid_coco.json
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']
    allow_empty: true

TestDataset:
  !CameraRadar_COCODataSet
    dataset_dir: /data1/zuokun/code/USV/Unmanned_ship_RTDETR_v2/prepared/sealand_single_tower_4km_super4
    radar_image_dir: ''
    camera_image_dir: ''
    anno_path: test_coco.json
    data_fields: ['image']
    allow_empty: true
